// src/lib/formula-library.ts

export type FormulaSubject = "matematika" | "fisika" | "kimia" | "biologi";

export type FormulaVariable = {
  sym: string;
  meaning: string;
};

export type Formula = {
  id: string;
  name: string;
  latex: string;              // tanpa $ — dirender sebagai blok
  description: string;
  subject: FormulaSubject;
  topic: string;
  variables?: FormulaVariable[];
  tips?: string;
  tags?: string[];
};

export const FORMULA_SUBJECTS: { id: FormulaSubject; label: string; short: string }[] = [
  { id: "matematika", label: "Matematika", short: "MTK" },
  { id: "fisika", label: "Fisika", short: "FIS" },
  { id: "kimia", label: "Kimia", short: "KIM" },
  { id: "biologi", label: "Biologi", short: "BIO" },
];

export const FORMULA_LIBRARY: Formula[] = [
  /* ============================ MATEMATIKA ============================ */
  {
    id: "mtk-abc",
    name: "Rumus ABC (Kuadrat)",
    latex: "x_{1,2} = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}",
    description: "Akar-akar persamaan kuadrat ax² + bx + c = 0.",
    subject: "matematika",
    topic: "Persamaan Kuadrat",
    variables: [
      { sym: "a,b,c", meaning: "koefisien dengan a ≠ 0" },
      { sym: "x", meaning: "variabel" },
    ],
    tips: "Wajib cek diskriminan dulu. D < 0 → tidak ada akar real.",
    tags: ["kuadrat", "abc", "akar"],
  },
  {
    id: "mtk-diskriminan",
    name: "Diskriminan",
    latex: "D = b^2 - 4ac",
    description: "Menentukan jenis akar persamaan kuadrat.",
    subject: "matematika",
    topic: "Persamaan Kuadrat",
    tips: "D > 0 (2 akar real beda) · D = 0 (kembar) · D < 0 (imajiner).",
    tags: ["diskriminan", "kuadrat"],
  },
  {
    id: "mtk-jumlah-akar",
    name: "Jumlah & Hasil Kali Akar",
    latex: "x_1 + x_2 = -\\frac{b}{a}, \\quad x_1 x_2 = \\frac{c}{a}",
    description: "Hubungan akar persamaan kuadrat tanpa mencari akarnya.",
    subject: "matematika",
    topic: "Persamaan Kuadrat",
    tags: ["vieta", "akar", "kuadrat"],
  },
  {
    id: "mtk-kuadrat-binomial",
    name: "Kuadrat Binomial",
    latex: "(a+b)^2 = a^2 + 2ab + b^2, \\quad (a-b)^2 = a^2 - 2ab + b^2",
    description: "Ekspansi bentuk kuadrat dua suku.",
    subject: "matematika",
    topic: "Aljabar",
    tips: "Ingat suku tengah 2ab — jangan lupa faktornya 2.",
    tags: ["aljabar", "binomial"],
  },
  {
    id: "mtk-selisih-kuadrat",
    name: "Selisih Kuadrat",
    latex: "a^2 - b^2 = (a-b)(a+b)",
    description: "Faktorisasi cepat bentuk selisih dua kuadrat.",
    subject: "matematika",
    topic: "Aljabar",
    tags: ["faktorisasi", "aljabar"],
  },
  {
    id: "mtk-barisan-arit",
    name: "Barisan Aritmetika",
    latex: "U_n = a + (n-1) b",
    description: "Suku ke-n barisan aritmetika dengan beda b.",
    subject: "matematika",
    topic: "Barisan & Deret",
    variables: [
      { sym: "a", meaning: "suku pertama U₁" },
      { sym: "b", meaning: "beda (Uₙ − Uₙ₋₁)" },
    ],
    tags: ["barisan", "aritmetika"],
  },
  {
    id: "mtk-deret-arit",
    name: "Deret Aritmetika",
    latex: "S_n = \\frac{n}{2}\\bigl(2a + (n-1)b\\bigr)",
    description: "Jumlah n suku pertama deret aritmetika.",
    subject: "matematika",
    topic: "Barisan & Deret",
    tags: ["deret", "aritmetika"],
  },
  {
    id: "mtk-barisan-geo",
    name: "Barisan Geometri",
    latex: "U_n = a \\, r^{\\,n-1}",
    description: "Suku ke-n barisan geometri dengan rasio r.",
    subject: "matematika",
    topic: "Barisan & Deret",
    tags: ["barisan", "geometri"],
  },
  {
    id: "mtk-deret-geo-takhingga",
    name: "Deret Geometri Tak Hingga",
    latex: "S_\\infty = \\frac{a}{1-r}, \\quad |r| < 1",
    description: "Jumlah tak hingga deret geometri konvergen.",
    subject: "matematika",
    topic: "Barisan & Deret",
    tips: "Hanya berlaku bila |r| < 1; jika |r| ≥ 1 deret divergen.",
    tags: ["deret", "geometri", "tak hingga"],
  },
  {
    id: "mtk-perbandingan-senilai",
    name: "Perbandingan Senilai",
    latex: "\\frac{a_1}{b_1} = \\frac{a_2}{b_2}",
    description: "Dua besaran naik/turun bersamaan.",
    subject: "matematika",
    topic: "Perbandingan",
    tips: "Kalau satu naik → yang lain naik → senilai (kali silang).",
    tags: ["perbandingan", "senilai"],
  },
  {
    id: "mtk-perbandingan-berbalik",
    name: "Perbandingan Berbalik Nilai",
    latex: "a_1 \\cdot b_1 = a_2 \\cdot b_2",
    description: "Dua besaran berbanding terbalik (satu naik, satu turun).",
    subject: "matematika",
    topic: "Perbandingan",
    tips: "Contoh klasik: jumlah pekerja vs waktu pengerjaan.",
    tags: ["perbandingan", "berbalik"],
  },
  {
    id: "mtk-pythagoras",
    name: "Teorema Pythagoras",
    latex: "c^2 = a^2 + b^2",
    description: "Sisi miring segitiga siku-siku.",
    subject: "matematika",
    topic: "Geometri",
    tags: ["pythagoras", "segitiga"],
  },
  {
    id: "mtk-lingkaran",
    name: "Luas & Keliling Lingkaran",
    latex: "L = \\pi r^2, \\quad K = 2\\pi r",
    description: "Luas dan keliling lingkaran berjari-jari r.",
    subject: "matematika",
    topic: "Geometri",
    tags: ["lingkaran", "luas", "keliling"],
  },
  {
    id: "mtk-rata-rata",
    name: "Rata-rata (Mean)",
    latex: "\\bar{x} = \\frac{\\sum x_i}{n}",
    description: "Rata-rata dari n data.",
    subject: "matematika",
    topic: "Statistika",
    tags: ["statistika", "mean"],
  },
  {
    id: "mtk-peluang",
    name: "Peluang Kejadian",
    latex: "P(A) = \\frac{n(A)}{n(S)}",
    description: "Peluang kejadian A dari ruang sampel S.",
    subject: "matematika",
    topic: "Peluang",
    tags: ["peluang"],
  },
  {
    id: "mtk-kombinasi",
    name: "Kombinasi",
    latex: "C(n,r) = \\binom{n}{r} = \\frac{n!}{r!\\,(n-r)!}",
    description: "Banyak cara memilih r dari n (tanpa urutan).",
    subject: "matematika",
    topic: "Peluang",
    tags: ["kombinasi", "permutasi"],
  },
  {
    id: "mtk-permutasi",
    name: "Permutasi",
    latex: "P(n,r) = \\frac{n!}{(n-r)!}",
    description: "Banyak cara menyusun r dari n (dengan urutan).",
    subject: "matematika",
    topic: "Peluang",
    tips: "Kalau urutan penting → permutasi. Kalau tidak → kombinasi.",
    tags: ["permutasi"],
  },

  /* ============================== FISIKA ============================== */
  {
    id: "fis-kecepatan",
    name: "Kecepatan",
    latex: "v = \\frac{s}{t}",
    description: "Kecepatan rata-rata dari jarak s dalam waktu t.",
    subject: "fisika",
    topic: "Kinematika",
    tags: ["kecepatan", "kinematika"],
  },
  {
    id: "fis-percepatan",
    name: "Percepatan",
    latex: "a = \\frac{\\Delta v}{\\Delta t}",
    description: "Perubahan kecepatan per satuan waktu.",
    subject: "fisika",
    topic: "Kinematika",
    tags: ["percepatan"],
  },
  {
    id: "fis-glbb-1",
    name: "GLBB — Kecepatan",
    latex: "v_t = v_0 + a t",
    description: "Kecepatan setelah waktu t pada GLBB.",
    subject: "fisika",
    topic: "Kinematika",
    tags: ["glbb", "kinematika"],
  },
  {
    id: "fis-glbb-2",
    name: "GLBB — Jarak",
    latex: "s = v_0 t + \\tfrac{1}{2} a t^2",
    description: "Jarak tempuh pada GLBB.",
    subject: "fisika",
    topic: "Kinematika",
    tags: ["glbb", "jarak"],
  },
  {
    id: "fis-glbb-3",
    name: "GLBB — Tanpa Waktu",
    latex: "v_t^2 = v_0^2 + 2 a s",
    description: "Hubungan kecepatan & jarak saat waktu tidak diketahui.",
    subject: "fisika",
    topic: "Kinematika",
    tags: ["glbb"],
  },
  {
    id: "fis-newton-2",
    name: "Hukum Newton II",
    latex: "F = m a",
    description: "Gaya netto = massa × percepatan.",
    subject: "fisika",
    topic: "Dinamika",
    tags: ["newton", "gaya"],
  },
  {
    id: "fis-berat",
    name: "Berat Benda",
    latex: "w = m g",
    description: "Gaya berat dengan percepatan gravitasi g ≈ 9,8 m/s².",
    subject: "fisika",
    topic: "Dinamika",
    tags: ["berat", "gravitasi"],
  },
  {
    id: "fis-gesek",
    name: "Gaya Gesek",
    latex: "f = \\mu \\, N",
    description: "Gaya gesek antara dua permukaan.",
    subject: "fisika",
    topic: "Dinamika",
    tips: "μs (statis) ≥ μk (kinetis). Saat bergerak, pakai μk.",
    tags: ["gesek", "gaya"],
  },
  {
    id: "fis-usaha",
    name: "Usaha",
    latex: "W = F \\, s \\cos\\theta",
    description: "Usaha oleh gaya F yang membentuk sudut θ terhadap perpindahan.",
    subject: "fisika",
    topic: "Usaha & Energi",
    tags: ["usaha"],
  },
  {
    id: "fis-energi-kinetik",
    name: "Energi Kinetik",
    latex: "E_k = \\tfrac{1}{2} m v^2",
    description: "Energi gerak benda bermassa m berkecepatan v.",
    subject: "fisika",
    topic: "Usaha & Energi",
    tags: ["energi", "kinetik"],
  },
  {
    id: "fis-energi-potensial",
    name: "Energi Potensial",
    latex: "E_p = m g h",
    description: "Energi potensial gravitasi pada ketinggian h.",
    subject: "fisika",
    topic: "Usaha & Energi",
    tags: ["energi", "potensial"],
  },
  {
    id: "fis-momentum",
    name: "Momentum",
    latex: "p = m v",
    description: "Momentum linear benda.",
    subject: "fisika",
    topic: "Momentum & Impuls",
    tags: ["momentum"],
  },
  {
    id: "fis-impuls",
    name: "Impuls",
    latex: "I = F \\, \\Delta t = \\Delta p",
    description: "Impuls = perubahan momentum.",
    subject: "fisika",
    topic: "Momentum & Impuls",
    tags: ["impuls"],
  },
  {
    id: "fis-tekanan",
    name: "Tekanan",
    latex: "P = \\frac{F}{A}",
    description: "Tekanan = gaya per satuan luas.",
    subject: "fisika",
    topic: "Fluida",
    tags: ["tekanan", "fluida"],
  },
  {
    id: "fis-hidrostatis",
    name: "Tekanan Hidrostatis",
    latex: "P = \\rho g h",
    description: "Tekanan zat cair pada kedalaman h.",
    subject: "fisika",
    topic: "Fluida",
    tags: ["hidrostatis"],
  },
  {
    id: "fis-archimedes",
    name: "Gaya Archimedes",
    latex: "F_a = \\rho \\, g \\, V",
    description: "Gaya apung pada benda yang tercelup.",
    subject: "fisika",
    topic: "Fluida",
    tags: ["archimedes", "apung"],
  },
  {
    id: "fis-kalor",
    name: "Kalor (Perubahan Suhu)",
    latex: "Q = m \\, c \\, \\Delta T",
    description: "Kalor untuk mengubah suhu benda.",
    subject: "fisika",
    topic: "Suhu & Kalor",
    tags: ["kalor", "suhu"],
  },
  {
    id: "fis-kalor-lebur",
    name: "Kalor Lebur / Uap",
    latex: "Q = m \\, L",
    description: "Kalor untuk perubahan wujud (tanpa perubahan suhu).",
    subject: "fisika",
    topic: "Suhu & Kalor",
    tags: ["kalor", "lebur"],
  },
  {
    id: "fis-ohm",
    name: "Hukum Ohm",
    latex: "V = I \\, R",
    description: "Tegangan = arus × hambatan.",
    subject: "fisika",
    topic: "Listrik",
    tags: ["ohm", "listrik"],
  },
  {
    id: "fis-daya-listrik",
    name: "Daya Listrik",
    latex: "P = V I = I^2 R = \\frac{V^2}{R}",
    description: "Daya disipasi pada komponen listrik.",
    subject: "fisika",
    topic: "Listrik",
    tags: ["daya", "listrik"],
  },
  {
    id: "fis-gelombang",
    name: "Cepat Rambat Gelombang",
    latex: "v = \\lambda f",
    description: "Kecepatan gelombang dari panjang gelombang & frekuensi.",
    subject: "fisika",
    topic: "Gelombang",
    tags: ["gelombang"],
  },
  {
    id: "fis-lensa",
    name: "Rumus Lensa / Cermin",
    latex: "\\frac{1}{f} = \\frac{1}{s} + \\frac{1}{s'}",
    description: "Hubungan fokus, jarak benda, dan jarak bayangan.",
    subject: "fisika",
    topic: "Optik",
    tips: "Perbesaran: M = |s'/s| = |h'/h|.",
    tags: ["lensa", "cermin", "optik"],
  },

  /* =============================== KIMIA ============================== */
  {
    id: "kim-mol-massa",
    name: "Mol dari Massa",
    latex: "n = \\frac{m}{M_r}",
    description: "Jumlah mol dari massa zat dan massa molar.",
    subject: "kimia",
    topic: "Stoikiometri",
    tags: ["mol", "stoikiometri"],
  },
  {
    id: "kim-jumlah-partikel",
    name: "Jumlah Partikel",
    latex: "N = n \\cdot N_A",
    description: "Jumlah partikel = mol × bilangan Avogadro (6,022×10²³).",
    subject: "kimia",
    topic: "Stoikiometri",
    tags: ["avogadro", "partikel"],
  },
  {
    id: "kim-volume-stp",
    name: "Volume Gas (STP)",
    latex: "V = n \\cdot 22{,}4 \\text{ L}",
    description: "Volume gas pada kondisi standar (0 °C, 1 atm).",
    subject: "kimia",
    topic: "Stoikiometri",
    tags: ["stp", "volume"],
  },
  {
    id: "kim-gas-ideal",
    name: "Persamaan Gas Ideal",
    latex: "P V = n R T",
    description: "Hubungan tekanan, volume, mol, dan suhu gas ideal.",
    subject: "kimia",
    topic: "Gas",
    variables: [
      { sym: "R", meaning: "0,082 L·atm/(mol·K)" },
      { sym: "T", meaning: "suhu (Kelvin)" },
    ],
    tags: ["gas", "ideal"],
  },
  {
    id: "kim-molaritas",
    name: "Molaritas",
    latex: "M = \\frac{n}{V}",
    description: "Konsentrasi larutan dalam mol per liter.",
    subject: "kimia",
    topic: "Larutan",
    tags: ["molaritas", "konsentrasi"],
  },
  {
    id: "kim-pengenceran",
    name: "Pengenceran",
    latex: "M_1 V_1 = M_2 V_2",
    description: "Menghitung konsentrasi setelah pengenceran.",
    subject: "kimia",
    topic: "Larutan",
    tags: ["pengenceran"],
  },
  {
    id: "kim-ph",
    name: "pH Larutan",
    latex: "\\text{pH} = -\\log[H^+]",
    description: "Tingkat keasaman larutan.",
    subject: "kimia",
    topic: "Asam-Basa",
    tips: "pH + pOH = 14 (pada 25 °C).",
    tags: ["ph", "asam", "basa"],
  },

  /* ============================== BIOLOGI ============================= */
  {
    id: "bio-fotosintesis",
    name: "Reaksi Fotosintesis",
    latex: "6CO_2 + 6H_2O \\xrightarrow{cahaya} C_6H_{12}O_6 + 6O_2",
    description: "Reaksi pembentukan glukosa pada tumbuhan hijau.",
    subject: "biologi",
    topic: "Metabolisme",
    tags: ["fotosintesis", "klorofil"],
  },
  {
    id: "bio-respirasi",
    name: "Respirasi Aerob",
    latex: "C_6H_{12}O_6 + 6O_2 \\to 6CO_2 + 6H_2O + \\text{energi}",
    description: "Pemecahan glukosa untuk menghasilkan energi (ATP).",
    subject: "biologi",
    topic: "Metabolisme",
    tags: ["respirasi", "atp"],
  },
  {
    id: "bio-pertumbuhan",
    name: "Pertumbuhan Populasi Eksponensial",
    latex: "N_t = N_0 \\cdot 2^{\\,n}",
    description: "Pertumbuhan populasi yang berlipat setiap generasi.",
    subject: "biologi",
    topic: "Populasi",
    tags: ["populasi", "pertumbuhan"],
  },
  {
    id: "bio-hardy-weinberg",
    name: "Hukum Hardy-Weinberg",
    latex: "p^2 + 2pq + q^2 = 1",
    description: "Kesetimbangan frekuensi alel dalam populasi ideal.",
    subject: "biologi",
    topic: "Genetika",
    variables: [
      { sym: "p", meaning: "frekuensi alel dominan" },
      { sym: "q", meaning: "frekuensi alel resesif, p + q = 1" },
    ],
    tags: ["genetika", "alel"],
  },
  {
    id: "bio-mendel",
    name: "Rasio Mendel",
    latex: "\\text{Monohibrid } 3:1, \\quad \\text{Dihibrid } 9:3:3:1",
    description: "Rasio fenotip F₂ pada persilangan Mendel.",
    subject: "biologi",
    topic: "Genetika",
    tags: ["mendel", "persilangan"],
  },

  /* ====================== TAMBAHAN — MATEMATIKA ======================= */
  {
    id: "mtk-log-kali",
    name: "Sifat Logaritma",
    latex: "{}^a\\log(xy) = {}^a\\log x + {}^a\\log y, \\quad {}^a\\log \\frac{x}{y} = {}^a\\log x - {}^a\\log y",
    description: "Perkalian jadi penjumlahan, pembagian jadi pengurangan.",
    subject: "matematika",
    topic: "Logaritma",
    tags: ["logaritma", "sifat"],
  },
  {
    id: "mtk-log-pangkat",
    name: "Logaritma Pangkat & Basis",
    latex: "{}^a\\log x^n = n\\,{}^a\\log x, \\quad {}^a\\log x = \\frac{{}^b\\log x}{{}^b\\log a}",
    description: "Menurunkan pangkat dan mengubah basis logaritma.",
    subject: "matematika",
    topic: "Logaritma",
    tips: "Ganti basis sangat berguna saat kalkulator hanya punya log dan ln.",
    tags: ["logaritma", "basis"],
  },
  {
    id: "mtk-eksponen",
    name: "Sifat Eksponen",
    latex: "a^m \\cdot a^n = a^{m+n}, \\quad \\frac{a^m}{a^n} = a^{m-n}, \\quad (a^m)^n = a^{mn}",
    description: "Aturan dasar perpangkatan.",
    subject: "matematika",
    topic: "Eksponen",
    tags: ["eksponen", "pangkat"],
  },
  {
    id: "mtk-identitas-trig",
    name: "Identitas Trigonometri Dasar",
    latex: "\\sin^2\\theta + \\cos^2\\theta = 1, \\quad \\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta}",
    description: "Identitas pokok yang paling sering dipakai.",
    subject: "matematika",
    topic: "Trigonometri",
    tags: ["trigonometri", "identitas"],
  },
  {
    id: "mtk-aturan-sinus",
    name: "Aturan Sinus",
    latex: "\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C} = 2R",
    description: "Hubungan sisi dan sudut pada sembarang segitiga.",
    subject: "matematika",
    topic: "Trigonometri",
    tags: ["sinus", "segitiga"],
  },
  {
    id: "mtk-aturan-cosinus",
    name: "Aturan Cosinus",
    latex: "a^2 = b^2 + c^2 - 2bc\\cos A",
    description: "Mencari sisi/sudut segitiga sembarang.",
    subject: "matematika",
    topic: "Trigonometri",
    tips: "Jika A = 90°, rumus ini menjadi Pythagoras.",
    tags: ["cosinus", "segitiga"],
  },
  {
    id: "mtk-luas-segitiga-trig",
    name: "Luas Segitiga (Trigonometri)",
    latex: "L = \\tfrac{1}{2} a b \\sin C",
    description: "Luas segitiga dari dua sisi dan sudut apitnya.",
    subject: "matematika",
    topic: "Trigonometri",
    tags: ["luas", "segitiga"],
  },
  {
    id: "mtk-turunan-pangkat",
    name: "Turunan Fungsi Pangkat",
    latex: "\\frac{d}{dx} x^n = n x^{n-1}",
    description: "Aturan turunan paling dasar.",
    subject: "matematika",
    topic: "Turunan",
    tags: ["turunan", "kalkulus"],
  },
  {
    id: "mtk-turunan-hasil-kali",
    name: "Turunan Hasil Kali & Bagi",
    latex: "(uv)' = u'v + uv', \\quad \\left(\\frac{u}{v}\\right)' = \\frac{u'v - uv'}{v^2}",
    description: "Aturan perkalian dan pembagian pada turunan.",
    subject: "matematika",
    topic: "Turunan",
    tags: ["turunan", "kalkulus"],
  },
  {
    id: "mtk-integral-pangkat",
    name: "Integral Fungsi Pangkat",
    latex: "\\int x^n \\, dx = \\frac{x^{n+1}}{n+1} + C, \\quad n \\neq -1",
    description: "Kebalikan dari turunan pangkat.",
    subject: "matematika",
    topic: "Integral",
    tips: "Jangan lupa +C untuk integral tak tentu.",
    tags: ["integral", "kalkulus"],
  },
  {
    id: "mtk-limit-trig",
    name: "Limit Trigonometri",
    latex: "\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1, \\quad \\lim_{x \\to 0} \\frac{\\tan x}{x} = 1",
    description: "Limit dasar yang sering muncul di soal.",
    subject: "matematika",
    topic: "Limit",
    tags: ["limit", "trigonometri"],
  },
  {
    id: "mtk-jarak-titik",
    name: "Jarak Dua Titik",
    latex: "d = \\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}",
    description: "Jarak pada bidang koordinat.",
    subject: "matematika",
    topic: "Geometri Analitik",
    tags: ["jarak", "koordinat"],
  },
  {
    id: "mtk-gradien",
    name: "Gradien Garis",
    latex: "m = \\frac{y_2 - y_1}{x_2 - x_1}",
    description: "Kemiringan garis melalui dua titik.",
    subject: "matematika",
    topic: "Geometri Analitik",
    tips: "Garis sejajar: m₁ = m₂. Tegak lurus: m₁·m₂ = −1.",
    tags: ["gradien", "garis"],
  },
  {
    id: "mtk-simpangan-baku",
    name: "Simpangan Baku",
    latex: "s = \\sqrt{\\frac{\\sum (x_i - \\bar{x})^2}{n}}",
    description: "Ukuran sebaran data terhadap rata-rata.",
    subject: "matematika",
    topic: "Statistika",
    tags: ["statistika", "simpangan"],
  },
  {
    id: "mtk-bunga-majemuk",
    name: "Bunga Majemuk",
    latex: "M_n = M_0 (1 + i)^n",
    description: "Nilai akhir modal setelah n periode berbunga.",
    subject: "matematika",
    topic: "Aritmetika Sosial",
    tags: ["bunga", "keuangan"],
  },
  {
    id: "mtk-skala",
    name: "Skala Peta",
    latex: "\\text{Skala} = \\frac{\\text{jarak pada peta}}{\\text{jarak sebenarnya}}",
    description: "Perbandingan jarak peta dan jarak asli.",
    subject: "matematika",
    topic: "Perbandingan",
    tags: ["skala", "peta"],
  },
  {
    id: "mtk-volume-bangun",
    name: "Volume Bangun Ruang",
    latex: "V_{\\text{balok}} = p\\,l\\,t, \\quad V_{\\text{tabung}} = \\pi r^2 t, \\quad V_{\\text{bola}} = \\tfrac{4}{3}\\pi r^3",
    description: "Volume bangun ruang yang paling sering keluar.",
    subject: "matematika",
    topic: "Geometri",
    tags: ["volume", "bangun ruang"],
  },

  /* ========================= TAMBAHAN — FISIKA ======================== */
  {
    id: "fis-gaya-sentripetal",
    name: "Gaya Sentripetal",
    latex: "F_s = \\frac{m v^2}{r} = m \\omega^2 r",
    description: "Gaya yang membuat benda bergerak melingkar.",
    subject: "fisika",
    topic: "Gerak Melingkar",
    tags: ["melingkar", "sentripetal"],
  },
  {
    id: "fis-kecepatan-sudut",
    name: "Kecepatan Sudut",
    latex: "\\omega = \\frac{2\\pi}{T} = 2\\pi f",
    description: "Hubungan kecepatan sudut, periode, dan frekuensi.",
    subject: "fisika",
    topic: "Gerak Melingkar",
    tags: ["periode", "frekuensi"],
  },
  {
    id: "fis-daya",
    name: "Daya Mekanik",
    latex: "P = \\frac{W}{t} = F v",
    description: "Laju melakukan usaha.",
    subject: "fisika",
    topic: "Usaha & Energi",
    tags: ["daya", "usaha"],
  },
  {
    id: "fis-hooke",
    name: "Hukum Hooke",
    latex: "F = k \\, \\Delta x",
    description: "Gaya pegas sebanding dengan pertambahan panjang.",
    subject: "fisika",
    topic: "Elastisitas",
    tips: "Energi pegas: Ep = ½k(Δx)².",
    tags: ["pegas", "hooke"],
  },
  {
    id: "fis-periode-pegas",
    name: "Periode Pegas & Bandul",
    latex: "T = 2\\pi\\sqrt{\\frac{m}{k}}, \\quad T = 2\\pi\\sqrt{\\frac{\\ell}{g}}",
    description: "Periode getaran pegas dan bandul sederhana.",
    subject: "fisika",
    topic: "Getaran",
    tags: ["periode", "getaran", "bandul"],
  },
  {
    id: "fis-kontinuitas",
    name: "Persamaan Kontinuitas",
    latex: "A_1 v_1 = A_2 v_2",
    description: "Debit fluida tetap di sepanjang pipa.",
    subject: "fisika",
    topic: "Fluida",
    tags: ["debit", "fluida"],
  },
  {
    id: "fis-bernoulli",
    name: "Asas Bernoulli",
    latex: "P + \\tfrac{1}{2}\\rho v^2 + \\rho g h = \\text{konstan}",
    description: "Kekekalan energi pada aliran fluida ideal.",
    subject: "fisika",
    topic: "Fluida",
    tags: ["bernoulli", "fluida"],
  },
  {
    id: "fis-azas-black",
    name: "Asas Black",
    latex: "Q_{\\text{lepas}} = Q_{\\text{terima}}",
    description: "Kalor yang dilepas benda panas = kalor yang diserap benda dingin.",
    subject: "fisika",
    topic: "Suhu & Kalor",
    tags: ["kalor", "black"],
  },
  {
    id: "fis-pemuaian",
    name: "Pemuaian Panjang",
    latex: "\\Delta L = L_0 \\, \\alpha \\, \\Delta T",
    description: "Pertambahan panjang benda karena kenaikan suhu.",
    subject: "fisika",
    topic: "Suhu & Kalor",
    tags: ["pemuaian", "suhu"],
  },
  {
    id: "fis-hambatan-seri",
    name: "Hambatan Seri & Paralel",
    latex: "R_s = R_1 + R_2 + \\dots, \\quad \\frac{1}{R_p} = \\frac{1}{R_1} + \\frac{1}{R_2} + \\dots",
    description: "Hambatan pengganti rangkaian listrik.",
    subject: "fisika",
    topic: "Listrik",
    tips: "Seri: arus sama. Paralel: tegangan sama.",
    tags: ["hambatan", "rangkaian"],
  },
  {
    id: "fis-hambatan-kawat",
    name: "Hambatan Kawat",
    latex: "R = \\rho \\frac{\\ell}{A}",
    description: "Hambatan bergantung jenis, panjang, dan luas penampang kawat.",
    subject: "fisika",
    topic: "Listrik",
    tags: ["hambatan", "kawat"],
  },
  {
    id: "fis-coulomb",
    name: "Hukum Coulomb",
    latex: "F = k \\frac{q_1 q_2}{r^2}",
    description: "Gaya antara dua muatan listrik (k ≈ 9×10⁹ N·m²/C²).",
    subject: "fisika",
    topic: "Listrik Statis",
    tags: ["coulomb", "muatan"],
  },
  {
    id: "fis-energi-listrik",
    name: "Energi Listrik",
    latex: "W = V I t = P t",
    description: "Energi yang dipakai alat listrik selama waktu t.",
    subject: "fisika",
    topic: "Listrik",
    tags: ["energi", "listrik"],
  },
  {
    id: "fis-gravitasi-newton",
    name: "Gaya Gravitasi Newton",
    latex: "F = G \\frac{m_1 m_2}{r^2}",
    description: "Gaya tarik antara dua benda bermassa.",
    subject: "fisika",
    topic: "Gravitasi",
    tags: ["gravitasi", "newton"],
  },
  {
    id: "fis-efek-doppler",
    name: "Efek Doppler",
    latex: "f_p = \\frac{v \\pm v_p}{v \\mp v_s} f_s",
    description: "Perubahan frekuensi karena gerak sumber/pendengar.",
    subject: "fisika",
    topic: "Gelombang",
    tips: "Tanda dipilih agar frekuensi naik saat saling mendekat.",
    tags: ["doppler", "bunyi"],
  },
  {
    id: "fis-intensitas-bunyi",
    name: "Taraf Intensitas Bunyi",
    latex: "TI = 10 \\log \\frac{I}{I_0}",
    description: "Tingkat kebisingan dalam desibel (I₀ = 10⁻¹² W/m²).",
    subject: "fisika",
    topic: "Gelombang",
    tags: ["bunyi", "desibel"],
  },
  {
    id: "fis-snellius",
    name: "Hukum Snellius",
    latex: "n_1 \\sin\\theta_1 = n_2 \\sin\\theta_2",
    description: "Pembiasan cahaya antar dua medium.",
    subject: "fisika",
    topic: "Optik",
    tags: ["pembiasan", "optik"],
  },
  {
    id: "fis-foton",
    name: "Energi Foton",
    latex: "E = h f = \\frac{h c}{\\lambda}",
    description: "Energi satu paket cahaya (h = 6,63×10⁻³⁴ J·s).",
    subject: "fisika",
    topic: "Fisika Modern",
    tags: ["foton", "kuantum"],
  },

  /* ========================== TAMBAHAN — KIMIA ======================== */
  {
    id: "kim-molalitas",
    name: "Molalitas",
    latex: "m = \\frac{n_{\\text{zat terlarut}}}{\\text{massa pelarut (kg)}}",
    description: "Konsentrasi berdasarkan massa pelarut.",
    subject: "kimia",
    topic: "Larutan",
    tags: ["molalitas", "konsentrasi"],
  },
  {
    id: "kim-fraksi-mol",
    name: "Fraksi Mol",
    latex: "X_A = \\frac{n_A}{n_A + n_B}",
    description: "Perbandingan mol satu komponen terhadap total mol.",
    subject: "kimia",
    topic: "Larutan",
    tags: ["fraksi mol"],
  },
  {
    id: "kim-poh",
    name: "pOH & Basa Kuat",
    latex: "\\text{pOH} = -\\log[OH^-], \\quad \\text{pH} = 14 - \\text{pOH}",
    description: "Menghitung pH larutan basa.",
    subject: "kimia",
    topic: "Asam-Basa",
    tags: ["poh", "basa"],
  },
  {
    id: "kim-asam-lemah",
    name: "pH Asam & Basa Lemah",
    latex: "[H^+] = \\sqrt{K_a \\cdot M}, \\quad [OH^-] = \\sqrt{K_b \\cdot M}",
    description: "Konsentrasi ion pada elektrolit lemah.",
    subject: "kimia",
    topic: "Asam-Basa",
    tags: ["asam lemah", "ka", "kb"],
  },
  {
    id: "kim-buffer",
    name: "Larutan Penyangga",
    latex: "[H^+] = K_a \\frac{n_{\\text{asam}}}{n_{\\text{garam}}}",
    description: "pH buffer asam lemah dan garamnya.",
    subject: "kimia",
    topic: "Asam-Basa",
    tips: "Buffer basa: [OH⁻] = Kb · (n basa / n garam).",
    tags: ["buffer", "penyangga"],
  },
  {
    id: "kim-titrasi",
    name: "Titrasi Asam-Basa",
    latex: "M_a V_a \\, a = M_b V_b \\, b",
    description: "Kesetaraan mol H⁺ dan OH⁻ saat titik ekuivalen.",
    subject: "kimia",
    topic: "Asam-Basa",
    variables: [
      { sym: "a, b", meaning: "valensi asam dan basa" },
    ],
    tags: ["titrasi"],
  },
  {
    id: "kim-ksp",
    name: "Hasil Kali Kelarutan",
    latex: "K_{sp} = [A^{m+}]^n [B^{n-}]^m",
    description: "Kesetimbangan garam yang sukar larut.",
    subject: "kimia",
    topic: "Kelarutan",
    tips: "Mengendap bila Qsp > Ksp.",
    tags: ["ksp", "kelarutan"],
  },
  {
    id: "kim-kc",
    name: "Tetapan Kesetimbangan",
    latex: "K_c = \\frac{[C]^c [D]^d}{[A]^a [B]^b}",
    description: "Perbandingan konsentrasi produk dan reaktan saat setimbang.",
    subject: "kimia",
    topic: "Kesetimbangan",
    tips: "Zat padat dan pelarut murni tidak dimasukkan.",
    tags: ["kesetimbangan", "kc"],
  },
  {
    id: "kim-kp",
    name: "Kp dari Kc",
    latex: "K_p = K_c (RT)^{\\Delta n}",
    description: "Hubungan tetapan tekanan dan konsentrasi gas.",
    subject: "kimia",
    topic: "Kesetimbangan",
    tags: ["kp", "kc", "gas"],
  },
  {
    id: "kim-laju-reaksi",
    name: "Laju Reaksi",
    latex: "v = k [A]^m [B]^n",
    description: "Hukum laju reaksi terhadap konsentrasi pereaksi.",
    subject: "kimia",
    topic: "Laju Reaksi",
    tags: ["laju", "orde"],
  },
  {
    id: "kim-laju-suhu",
    name: "Kenaikan Laju karena Suhu",
    latex: "v_2 = v_1 \\cdot n^{\\frac{\\Delta T}{T_{\\text{kelipatan}}}}",
    description: "Laju menjadi n kali setiap kenaikan suhu tertentu.",
    subject: "kimia",
    topic: "Laju Reaksi",
    tags: ["laju", "suhu"],
  },
  {
    id: "kim-entalpi",
    name: "Perubahan Entalpi",
    latex: "\\Delta H = \\sum \\Delta H_f^\\circ(\\text{produk}) - \\sum \\Delta H_f^\\circ(\\text{reaktan})",
    description: "Kalor reaksi dari data entalpi pembentukan.",
    subject: "kimia",
    topic: "Termokimia",
    tips: "ΔH negatif = eksoterm (melepas kalor).",
    tags: ["entalpi", "termokimia"],
  },
  {
    id: "kim-penurunan-titik-beku",
    name: "Sifat Koligatif — Titik Beku & Didih",
    latex: "\\Delta T_f = K_f \\cdot m \\cdot i, \\quad \\Delta T_b = K_b \\cdot m \\cdot i",
    description: "Perubahan titik beku dan titik didih larutan.",
    subject: "kimia",
    topic: "Sifat Koligatif",
    variables: [{ sym: "i", meaning: "faktor van't Hoff, 1 + (n−1)α" }],
    tags: ["koligatif", "titik beku"],
  },
  {
    id: "kim-osmotik",
    name: "Tekanan Osmotik",
    latex: "\\pi = M R T i",
    description: "Tekanan osmotik larutan.",
    subject: "kimia",
    topic: "Sifat Koligatif",
    tags: ["osmotik", "koligatif"],
  },
  {
    id: "kim-faraday",
    name: "Hukum Faraday",
    latex: "m = \\frac{e \\cdot i \\cdot t}{96500}",
    description: "Massa zat hasil elektrolisis.",
    subject: "kimia",
    topic: "Elektrokimia",
    variables: [{ sym: "e", meaning: "massa ekivalen = Ar / valensi" }],
    tags: ["faraday", "elektrolisis"],
  },
  {
    id: "kim-potensial-sel",
    name: "Potensial Sel",
    latex: "E^\\circ_{\\text{sel}} = E^\\circ_{\\text{katoda}} - E^\\circ_{\\text{anoda}}",
    description: "Beda potensial sel volta.",
    subject: "kimia",
    topic: "Elektrokimia",
    tips: "E°sel positif → reaksi berlangsung spontan.",
    tags: ["volta", "potensial"],
  },

  /* ========================= TAMBAHAN — BIOLOGI ======================= */
  {
    id: "bio-atp-respirasi",
    name: "Hasil ATP Respirasi Aerob",
    latex: "\\text{Glikolisis } 2 + \\text{Siklus Krebs } 2 + \\text{Transpor elektron } 34 = 38\\ \\text{ATP}",
    description: "Rincian energi dari satu molekul glukosa.",
    subject: "biologi",
    topic: "Metabolisme",
    tips: "Sering ditulis 36 ATP bila memperhitungkan biaya transpor NADH.",
    tags: ["atp", "respirasi"],
  },
  {
    id: "bio-gamet",
    name: "Jumlah Macam Gamet",
    latex: "\\text{Macam gamet} = 2^n",
    description: "n = jumlah pasangan gen heterozigot.",
    subject: "biologi",
    topic: "Genetika",
    tags: ["gamet", "genetika"],
  },
  {
    id: "bio-perbandingan-f2",
    name: "Kombinasi F2 Dihibrid",
    latex: "\\text{Kotak Punnett} = 4^n",
    description: "Banyak kombinasi keturunan untuk n sifat beda.",
    subject: "biologi",
    topic: "Genetika",
    tags: ["punnett", "dihibrid"],
  },
  {
    id: "bio-indeks-keanekaragaman",
    name: "Indeks Keanekaragaman Shannon",
    latex: "H' = -\\sum p_i \\ln p_i",
    description: "Ukuran keanekaragaman jenis dalam suatu komunitas.",
    subject: "biologi",
    topic: "Ekologi",
    variables: [{ sym: "p_i", meaning: "proporsi individu jenis ke-i" }],
    tags: ["ekologi", "keanekaragaman"],
  },
  {
    id: "bio-laju-transpirasi",
    name: "Laju Transpirasi",
    latex: "\\text{Laju} = \\frac{\\text{volume air hilang}}{\\text{luas daun} \\times \\text{waktu}}",
    description: "Kecepatan penguapan air lewat daun.",
    subject: "biologi",
    topic: "Fisiologi Tumbuhan",
    tags: ["transpirasi", "tumbuhan"],
  },
  {
    id: "bio-pembelahan-sel",
    name: "Jumlah Sel Hasil Pembelahan",
    latex: "N = N_0 \\cdot 2^{t/g}",
    description: "Pertumbuhan jumlah sel dengan waktu generasi g.",
    subject: "biologi",
    topic: "Sel",
    tags: ["mitosis", "sel"],
  },
  {
    id: "bio-kromosom",
    name: "Kromosom Mitosis vs Meiosis",
    latex: "\\text{Mitosis: } 2n \\to 2n, \\quad \\text{Meiosis: } 2n \\to n",
    description: "Perubahan jumlah kromosom pada pembelahan sel.",
    subject: "biologi",
    topic: "Sel",
    tips: "Mitosis menghasilkan 2 sel identik, meiosis 4 sel haploid.",
    tags: ["mitosis", "meiosis"],
  },
  {
    id: "bio-imt",
    name: "Indeks Massa Tubuh",
    latex: "IMT = \\frac{m}{t^2}",
    description: "Massa (kg) dibagi kuadrat tinggi (m).",
    subject: "biologi",
    topic: "Tubuh Manusia",
    tags: ["imt", "kesehatan"],
  },
  {
    id: "bio-curah-jantung",
    name: "Curah Jantung",
    latex: "CO = HR \\times SV",
    description: "Volume darah per menit = denyut per menit × volume sekuncup.",
    subject: "biologi",
    topic: "Tubuh Manusia",
    tags: ["jantung", "sirkulasi"],
  },
];

/** Daftar tag unik untuk suggestion / filter lanjutan. */
export const FORMULA_ALL_TAGS: string[] = Array.from(
  new Set(FORMULA_LIBRARY.flatMap((f) => f.tags ?? [])),
).sort();