/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAuditoryRouteImport } from './routes/_authenticated/auditory'
import { Route as AuthenticatedGuideRouteImport } from './routes/_authenticated/guide'
import { Route as AuthenticatedKinestheticRouteImport } from './routes/_authenticated/kinesthetic'
import { Route as AuthenticatedLectureRouteImport } from './routes/_authenticated/lecture'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedPredictorRouteImport } from './routes/_authenticated/predictor'
import { Route as AuthenticatedStemRouteImport } from './routes/_authenticated/stem'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedStemIndexRouteImport } from './routes/_authenticated/stem.index'
import { Route as AuthenticatedStemAnalyticsRouteImport } from './routes/_authenticated/stem.analytics'
import { Route as AuthenticatedStemBookmarksRouteImport } from './routes/_authenticated/stem.bookmarks'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoryRoute = AuthenticatedAuditoryRouteImport.update({
  id: '/auditory',
  path: '/auditory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuideRoute = AuthenticatedGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKinestheticRoute =
  AuthenticatedKinestheticRouteImport.update({
    id: '/kinesthetic',
    path: '/kinesthetic',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLectureRoute = AuthenticatedLectureRouteImport.update({
  id: '/lecture',
  path: '/lecture',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPredictorRoute = AuthenticatedPredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStemRoute = AuthenticatedStemRouteImport.update({
  id: '/stem',
  path: '/stem',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedStemIndexRoute = AuthenticatedStemIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStemRoute,
} as any)
const AuthenticatedStemAnalyticsRoute =
  AuthenticatedStemAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedStemRoute,
  } as any)
const AuthenticatedStemBookmarksRoute =
  AuthenticatedStemBookmarksRouteImport.update({
    id: '/bookmarks',
    path: '/bookmarks',
    getParentRoute: () => AuthenticatedStemRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auditory': typeof AuthenticatedAuditoryRoute
  '/guide': typeof AuthenticatedGuideRoute
  '/kinesthetic': typeof AuthenticatedKinestheticRoute
  '/lecture': typeof AuthenticatedLectureRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/predictor': typeof AuthenticatedPredictorRoute
  '/stem': typeof AuthenticatedStemRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/stem/analytics': typeof AuthenticatedStemAnalyticsRoute
  '/stem/bookmarks': typeof AuthenticatedStemBookmarksRoute
  '/stem/': typeof AuthenticatedStemIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/auditory': typeof AuthenticatedAuditoryRoute
  '/guide': typeof AuthenticatedGuideRoute
  '/kinesthetic': typeof AuthenticatedKinestheticRoute
  '/lecture': typeof AuthenticatedLectureRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/predictor': typeof AuthenticatedPredictorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/stem/analytics': typeof AuthenticatedStemAnalyticsRoute
  '/stem/bookmarks': typeof AuthenticatedStemBookmarksRoute
  '/stem': typeof AuthenticatedStemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/auditory': typeof AuthenticatedAuditoryRoute
  '/_authenticated/guide': typeof AuthenticatedGuideRoute
  '/_authenticated/kinesthetic': typeof AuthenticatedKinestheticRoute
  '/_authenticated/lecture': typeof AuthenticatedLectureRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/predictor': typeof AuthenticatedPredictorRoute
  '/_authenticated/stem': typeof AuthenticatedStemRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/stem/analytics': typeof AuthenticatedStemAnalyticsRoute
  '/_authenticated/stem/bookmarks': typeof AuthenticatedStemBookmarksRoute
  '/_authenticated/stem/': typeof AuthenticatedStemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auditory'
    | '/guide'
    | '/kinesthetic'
    | '/lecture'
    | '/planner'
    | '/predictor'
    | '/stem'
    | '/auth/callback'
    | '/stem/analytics'
    | '/stem/bookmarks'
    | '/stem/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/auditory'
    | '/guide'
    | '/kinesthetic'
    | '/lecture'
    | '/planner'
    | '/predictor'
    | '/auth/callback'
    | '/'
    | '/stem/analytics'
    | '/stem/bookmarks'
    | '/stem'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/auditory'
    | '/_authenticated/guide'
    | '/_authenticated/kinesthetic'
    | '/_authenticated/lecture'
    | '/_authenticated/planner'
    | '/_authenticated/predictor'
    | '/_authenticated/stem'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/stem/analytics'
    | '/_authenticated/stem/bookmarks'
    | '/_authenticated/stem/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditory': {
      id: '/_authenticated/auditory'
      path: '/auditory'
      fullPath: '/auditory'
      preLoaderRoute: typeof AuthenticatedAuditoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guide': {
      id: '/_authenticated/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthenticatedGuideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kinesthetic': {
      id: '/_authenticated/kinesthetic'
      path: '/kinesthetic'
      fullPath: '/kinesthetic'
      preLoaderRoute: typeof AuthenticatedKinestheticRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lecture': {
      id: '/_authenticated/lecture'
      path: '/lecture'
      fullPath: '/lecture'
      preLoaderRoute: typeof AuthenticatedLectureRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/predictor': {
      id: '/_authenticated/predictor'
      path: '/predictor'
      fullPath: '/predictor'
      preLoaderRoute: typeof AuthenticatedPredictorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stem': {
      id: '/_authenticated/stem'
      path: '/stem'
      fullPath: '/stem'
      preLoaderRoute: typeof AuthenticatedStemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/stem/': {
      id: '/_authenticated/stem/'
      path: '/'
      fullPath: '/stem/'
      preLoaderRoute: typeof AuthenticatedStemIndexRouteImport
      parentRoute: typeof AuthenticatedStemRoute
    }
    '/_authenticated/stem/analytics': {
      id: '/_authenticated/stem/analytics'
      path: '/analytics'
      fullPath: '/stem/analytics'
      preLoaderRoute: typeof AuthenticatedStemAnalyticsRouteImport
      parentRoute: typeof AuthenticatedStemRoute
    }
    '/_authenticated/stem/bookmarks': {
      id: '/_authenticated/stem/bookmarks'
      path: '/bookmarks'
      fullPath: '/stem/bookmarks'
      preLoaderRoute: typeof AuthenticatedStemBookmarksRouteImport
      parentRoute: typeof AuthenticatedStemRoute
    }
  }
}

interface AuthenticatedStemRouteChildren {
  AuthenticatedStemAnalyticsRoute: typeof AuthenticatedStemAnalyticsRoute
  AuthenticatedStemBookmarksRoute: typeof AuthenticatedStemBookmarksRoute
  AuthenticatedStemIndexRoute: typeof AuthenticatedStemIndexRoute
}

const AuthenticatedStemRouteChildren: AuthenticatedStemRouteChildren = {
  AuthenticatedStemAnalyticsRoute: AuthenticatedStemAnalyticsRoute,
  AuthenticatedStemBookmarksRoute: AuthenticatedStemBookmarksRoute,
  AuthenticatedStemIndexRoute: AuthenticatedStemIndexRoute,
}

const AuthenticatedStemRouteWithChildren =
  AuthenticatedStemRoute._addFileChildren(AuthenticatedStemRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditoryRoute: typeof AuthenticatedAuditoryRoute
  AuthenticatedGuideRoute: typeof AuthenticatedGuideRoute
  AuthenticatedKinestheticRoute: typeof AuthenticatedKinestheticRoute
  AuthenticatedLectureRoute: typeof AuthenticatedLectureRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedPredictorRoute: typeof AuthenticatedPredictorRoute
  AuthenticatedStemRoute: typeof AuthenticatedStemRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditoryRoute: AuthenticatedAuditoryRoute,
  AuthenticatedGuideRoute: AuthenticatedGuideRoute,
  AuthenticatedKinestheticRoute: AuthenticatedKinestheticRoute,
  AuthenticatedLectureRoute: AuthenticatedLectureRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedPredictorRoute: AuthenticatedPredictorRoute,
  AuthenticatedStemRoute: AuthenticatedStemRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
